//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSampleTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
    {
        public long ProductID { get; set; }

        [DisplayName("Product Name")]
        public string ProductName { get; set; }

        [DisplayName("Description")]
        public string ProductDescription { get; set; }

        [DisplayName("Price")]
        public double ProductPrice { get; set; }

        [DisplayName("Create Date")]
        public System.DateTime ProductCreatedDate { get; set; }

        [DisplayName("Modified Date")]
        public Nullable<System.DateTime> ProductModifiedDate { get; set; }

        [DisplayName("Category")]
        public long ProductCategoryId { get; set; }

        [DisplayName("Quantity")]
        public Nullable<int> ProductQuantity { get; set; }

        [DisplayName("Picture")]
        public long ProductPictureId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Picture Picture { get; set; }
    }
}
